### ISSUE TITLE
new rotations

### ISSUE THREAD

**Issue by mvigneras** [AWestover/AI#1]
"F":{"indpairs":[(1,4),(4,3),(3,5),(5,1)], "indflips":(1)},
"Fi":{"indpairs":[(4,1),(3,4),(5,3),(1,5)], "indflips":(1)},
"B":{"indpairs":[(4,1),(3,4),(5,3),(1,5)], "indflips":(0)},
"Bi":{"indpairs":[(1,4),(4,3),(3,5),(5,1)], "indflips":(0)},
"D":{"indpairs":[(4,0),(0,5),(5,2),(2,4)], "indflips":(1)},
"Di":{"indpairs":[(0,4),(5,0),(2,5),(4,2)], "indflips":(1)},

**Comment by awestover** [comment]
thanks, I added them. Maybe fork it and check to make sure that they work. I think that I fixed the 2by2 rotation for my simulation at: https://awestover.github.io/AI/cube/templates/
