### ISSUE TITLE
Algs and rec

### ISSUE THREAD

**Issue by mvigneras** [AWestover/AI#2]
#PLL Algs
algs["Diagonal PLL"] = ['Ri','F','Ri','B','B','R','Fi','Ri','B','B','R','R']
algs["Parralel PLL switch"] = algs["Diagonal PLL"]+['Ui']

#White recognition
states['whiteFace'] = [([3, [0,0]], "W", True),([3, [0,1]], "W", True),([3, [1,0]], "W", True),([3, [1,1]], "W", True), 
([0, [1,0]], "G", True),([0, [1,1]], "G", True), 
([2, [1,0]], "B", True),([2, [1,1]], "B", True),
([4, [1,0]], "O", True),([4, [1,1]], "O", True),
([5, [1,0]], "R", True),([5, [1,1]], "R", True)]

**Comment by awestover** [comment]
Note: will have more hardcoded version of white face detection and yellow face detection etc
actual if statements not the detection for loop

**Comment by awestover** [comment]
Added these algorithms. Still need more though
